const API_BASE=window.AI_VOICE_API||'http://127.0.0.1:8000';
const $=id=>document.getElementById(id);
const textInput=$('textInput'),voiceSelect=$('voiceSelect'),engineSelect=$('engineSelect'),languageSelect=$('languageSelect'),speed=$('speed'),pitch=$('pitch');
let voices=[],currentAudioUrl=null;
const projectKey='laxman-ai-voice-projects';
function setStatus(title,text){$('statusTitle').textContent=title;$('statusText').textContent=text}
function updateCounter(){$('counter').textContent=`${textInput.value.length.toLocaleString()} / 12,000`}
function browserVoices(){if(languageSelect.value!=='en'&&engineSelect.value!=='browser')return;voices=speechSynthesis.getVoices().map((v,i)=>({id:`browser-${i}`,name:v.name,language:v.lang,local:true,voice:v}));if(engineSelect.value==='browser'){voiceSelect.innerHTML='';voices.forEach(v=>{const o=document.createElement('option');o.value=v.id;o.textContent=`${v.name} · ${v.language}`;voiceSelect.appendChild(o)});if(!voices.length){const o=document.createElement('option');o.value='browser-default';o.textContent='Browser default';voiceSelect.appendChild(o)}}}
async function localVoices(){try{const r=await fetch(`${API_BASE}/voices`,{signal:AbortSignal.timeout(1800)});if(!r.ok)throw Error();return(await r.json()).voices||[]}catch{return null}}
async function detect(){setStatus('Checking backend…','Connecting to your local AI voice server');const local=await localVoices();if(local?.length){voices=local;voiceSelect.innerHTML='';local.filter(v=>languageSelect.value==='ne'?v.language?.startsWith('ne'):true).forEach(v=>{const o=document.createElement('option');o.value=v.id;o.textContent=`${v.name} · ${v.language}`;voiceSelect.appendChild(o)});$('engineBadge').textContent='Neural API connected';setStatus('AI voice ready','Local neural voice engine detected');return}browserVoices();$('engineBadge').textContent='Browser fallback';setStatus('Browser fallback','Start FastAPI for downloadable neural Nepali speech')}
async function generate(){const text=textInput.value.trim();if(!text)return setStatus('Nothing to generate','Enter some text first');const requested=engineSelect.value;const language=languageSelect.value;if(requested!=='browser')try{setStatus('Generating AI voice…','Running local neural inference');const r=await fetch(`${API_BASE}/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,voice:voiceSelect.value,language,speed:+speed.value,pitch:+pitch.value,format:'wav'})});if(!r.ok)throw Error(await r.text());const blob=await r.blob();if(currentAudioUrl)URL.revokeObjectURL(currentAudioUrl);currentAudioUrl=URL.createObjectURL(blob);$('audioPlayer').src=currentAudioUrl;$('downloadBtn').disabled=false;$('outputMeta').textContent=`Neural WAV · ${(blob.size/1024).toFixed(1)} KB · ${language==='ne'?'Nepali':'English'}`;$('engineBadge').textContent=language==='ne'?'Nepali neural':'Local neural';setStatus('Generated','Your AI voice is ready');return}catch(e){if(requested==='local'||language==='ne'){setStatus('Neural generation failed',e.message.slice(0,160));return}}
const utterance=new SpeechSynthesisUtterance(text);const selected=voices.find(v=>v.id===voiceSelect.value);if(selected?.voice)utterance.voice=selected.voice;utterance.lang=language==='ne'?'ne-NP':'en-US';utterance.rate=+speed.value;utterance.pitch=+pitch.value;utterance.onstart=()=>setStatus('Speaking…','Browser SpeechSynthesis');utterance.onend=()=>setStatus('Ready','Speech finished');utterance.onerror=()=>setStatus('Speech error','Try another browser voice');speechSynthesis.cancel();speechSynthesis.speak(utterance);$('outputMeta').textContent='Browser speech · download unavailable in fallback mode';$('downloadBtn').disabled=true}
async function batchGenerate(){const text=textInput.value.trim();if(!text)return setStatus('Nothing to batch','Paste your full creator script first');const maxChars=+$('sceneSize').value;$('batchBtn').disabled=true;$('batchProgress').style.width='12%';$('batchMeta').textContent='Preparing scenes and generating neural audio…';setStatus('Creator batch running','Generating scene-by-scene neural audio');try{const r=await fetch(`${API_BASE}/batch/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,voice:voiceSelect.value||'nepali-vits',language:languageSelect.value,speed:+speed.value,max_chars:maxChars})});if(!r.ok)throw Error(await r.text());const blob=await r.blob();$('batchProgress').style.width='100%';$('batchMeta').textContent=`Batch ready · ${(blob.size/1024/1024).toFixed(2)} MB ZIP`;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='laxman-ai-voice-creator-batch.zip';a.click();setStatus('Batch complete','ZIP downloaded with scene assets')}catch(e){$('batchProgress').style.width='0%';$('batchMeta').textContent='Batch failed. Check that FastAPI is running and the neural model is ready.';setStatus('Batch failed',e.message.slice(0,160))}finally{$('batchBtn').disabled=false}}
function updateSceneCount(){const max=+$('sceneSize').value||900;const text=textInput.value.trim();$('sceneCount').textContent=text?`~${Math.max(1,Math.ceil(text.length/max))} scenes`:'0 scenes'}
function refreshLanguage(){detect();updateSceneCount()}
function projectPayload(){return{text:textInput.value,voice:voiceSelect.value,language:languageSelect.value,speed:+speed.value,pitch:+pitch.value,engine:engineSelect.value,updatedAt:new Date().toISOString()}}
async function saveProject(){const name=$('projectName').value.trim()||'Untitled Voice Project',payload=projectPayload();try{const r=await fetch(`${API_BASE}/projects`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,payload})});if(r.ok)return setStatus('Project saved','Saved to SQLite backend')}catch{}const p=JSON.parse(localStorage.getItem(projectKey)||'[]');p.unshift({name,payload});localStorage.setItem(projectKey,JSON.stringify(p.slice(0,30)));setStatus('Project saved','Saved in this browser')}
async function loadLatest(){try{const r=await fetch(`${API_BASE}/projects`);if(r.ok){const d=await r.json(),p=d.projects?.[0];if(p)return applyProject(p.name,p.payload)}}catch{}const p=(JSON.parse(localStorage.getItem(projectKey)||'[]'))[0];if(p)applyProject(p.name,p.payload);else setStatus('No project','Save a project first')}
function applyProject(name,p){$('projectName').value=name||'Untitled Voice Project';textInput.value=p.text||'';speed.value=p.speed||1;pitch.value=p.pitch||1;engineSelect.value=p.engine||'auto';languageSelect.value=p.language||'ne';updateCounter();updateSceneCount();$('speedOut').textContent=`${(+speed.value).toFixed(2)}×`;$('pitchOut').textContent=`${(+pitch.value).toFixed(2)}×`;detect();setStatus('Project loaded','Ready to continue editing')}
textInput.addEventListener('input',()=>{updateCounter();updateSceneCount()});languageSelect.onchange=refreshLanguage;$('clearBtn').onclick=()=>{textInput.value='';updateCounter();updateSceneCount()};$('sampleBtn').onclick=()=>{textInput.value='नमस्ते! म नेपाली भाषामा प्राकृतिक AI आवाज निर्माण गर्दैछु। आज हामी प्रविधि, शिक्षा र नेपालको भविष्यबारे कुरा गर्नेछौँ। नेपालको नयाँ पुस्ताले AI, डिजिटल सीप र सिर्जनात्मक प्रविधिको प्रयोग गरेर विश्वस्तरमा काम गर्न सक्छ।';languageSelect.value='ne';updateCounter();updateSceneCount()};$('generateBtn').onclick=generate;$('batchBtn').onclick=batchGenerate;$('sceneSize').onchange=updateSceneCount;$('saveProjectBtn').onclick=saveProject;$('loadProjectBtn').onclick=loadLatest;speed.oninput=()=>$('speedOut').textContent=`${(+speed.value).toFixed(2)}×`;pitch.oninput=()=>$('pitchOut').textContent=`${(+pitch.value).toFixed(2)}×`;$('downloadBtn').onclick=()=>{if(!currentAudioUrl)return;const a=document.createElement('a');a.href=currentAudioUrl;a.download='laxman-nepali-ai-voice.wav';a.click()};$('themeBtn').onclick=()=>document.documentElement.classList.toggle('light');speechSynthesis.onvoiceschanged=browserVoices;updateCounter();updateSceneCount();browserVoices();detect();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
