const API_BASE = window.AI_VOICE_API || 'http://127.0.0.1:8000';
const $ = id => document.getElementById(id); const textInput=$('textInput'), voiceSelect=$('voiceSelect'), engineSelect=$('engineSelect'), speed=$('speed'), pitch=$('pitch'); let voices=[], currentAudioUrl=null; const projectKey='laxman-ai-voice-projects';
function setStatus(title,text){$('statusTitle').textContent=title;$('statusText').textContent=text} function updateCounter(){$('counter').textContent=`${textInput.value.length.toLocaleString()} / 12,000`}
function browserVoices(){voices=speechSynthesis.getVoices().map((v,i)=>({id:`browser-${i}`,name:v.name,language:v.lang,local:true,voice:v}));if(engineSelect.value!=='browser'&&document.querySelector('#engineBadge')?.textContent.includes('Local'))return;voiceSelect.innerHTML='';voices.forEach(v=>{const o=document.createElement('option');o.value=v.id;o.textContent=`${v.name} · ${v.language}`;voiceSelect.appendChild(o)});if(!voices.length){const o=document.createElement('option');o.value='browser-default';o.textContent='Browser default';voiceSelect.appendChild(o)}}
async function localVoices(){try{const r=await fetch(`${API_BASE}/voices`,{signal:AbortSignal.timeout(1600)});if(!r.ok)throw Error();return(await r.json()).voices||[]}catch{return null}}
async function detect(){const local=await localVoices();if(local?.length){voices=local;voiceSelect.innerHTML='';local.forEach(v=>{const o=document.createElement('option');o.value=v.id;o.textContent=`${v.name} · ${v.language}`;voiceSelect.appendChild(o)});$('engineBadge').textContent='Local neural engine';setStatus('Local engine ready','Kokoro voice catalog detected');return}browserVoices();$('engineBadge').textContent='Browser fallback';setStatus('Ready','Browser SpeechSynthesis available')}
async function generate(){const text=textInput.value.trim();if(!text)return setStatus('Nothing to generate','Enter some text first');const requested=engineSelect.value;if(requested!=='browser')try{setStatus('Generating…','Running local neural inference');const r=await fetch(`${API_BASE}/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,voice:voiceSelect.value,speed:+speed.value,pitch:+pitch.value,format:'wav'})});if(!r.ok)throw Error(await r.text());const blob=await r.blob();if(currentAudioUrl)URL.revokeObjectURL(currentAudioUrl);currentAudioUrl=URL.createObjectURL(blob);$('audioPlayer').src=currentAudioUrl;$('downloadBtn').disabled=false;$('outputMeta').textContent=`Generated WAV · ${(blob.size/1024).toFixed(1)} KB`;$('engineBadge').textContent='Local neural engine';setStatus('Generated','Audio is ready');return}catch(e){if(requested==='local'){setStatus('Local engine unavailable','Install the model and start FastAPI');return}}const utterance=new SpeechSynthesisUtterance(text);const selected=voices.find(v=>v.id===voiceSelect.value);if(selected?.voice)utterance.voice=selected.voice;utterance.rate=+speed.value;utterance.pitch=+pitch.value;utterance.onstart=()=>setStatus('Speaking…','Browser SpeechSynthesis');utterance.onend=()=>setStatus('Ready','Speech finished');utterance.onerror=()=>setStatus('Speech error','Try another browser voice');speechSynthesis.cancel();speechSynthesis.speak(utterance);$('outputMeta').textContent='Browser speech · download unavailable in fallback mode';$('downloadBtn').disabled=true}
function projectPayload(){return{text:textInput.value,voice:voiceSelect.value,speed:+speed.value,pitch:+pitch.value,engine:engineSelect.value,updatedAt:new Date().toISOString()}}
async function saveProject(){const name=$('projectName').value.trim()||'Untitled Voice Project',payload=projectPayload();try{const r=await fetch(`${API_BASE}/projects`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,payload})});if(r.ok)return setStatus('Project saved','Saved to SQLite backend')}catch{}const p=JSON.parse(localStorage.getItem(projectKey)||'[]');p.unshift({name,payload});localStorage.setItem(projectKey,JSON.stringify(p.slice(0,30)));setStatus('Project saved','Saved in this browser')}
async function loadLatest(){try{const r=await fetch(`${API_BASE}/projects`);if(r.ok){const d=await r.json();const p=d.projects?.[0];if(p)return applyProject(p.name,p.payload)}}catch{}const p=(JSON.parse(localStorage.getItem(projectKey)||'[]'))[0];if(p)applyProject(p.name,p.payload);else setStatus('No project','Save a project first')}
function applyProject(name,p){$('projectName').value=name||'Untitled Voice Project';textInput.value=p.text||'';speed.value=p.speed||1;pitch.value=p.pitch||1;engineSelect.value=p.engine||'auto';updateCounter();$('speedOut').textContent=`${(+speed.value).toFixed(2)}×`;$('pitchOut').textContent=`${(+pitch.value).toFixed(2)}×`;if(p.voice)voiceSelect.value=p.voice;setStatus('Project loaded','Ready to continue editing')}
textInput.addEventListener('input',updateCounter);$('clearBtn').onclick=()=>{textInput.value='';updateCounter()};$('sampleBtn').onclick=()=>{textInput.value='Namaste everyone. Welcome to Laxman AI Voice. This is a local-first neural text to speech studio for creators.';updateCounter()};$('generateBtn').onclick=generate;$('saveProjectBtn').onclick=saveProject;$('loadProjectBtn').onclick=loadLatest;speed.oninput=()=>$('speedOut').textContent=`${(+speed.value).toFixed(2)}×`;pitch.oninput=()=>$('pitchOut').textContent=`${(+pitch.value).toFixed(2)}×`;$('downloadBtn').onclick=()=>{if(!currentAudioUrl)return;const a=document.createElement('a');a.href=currentAudioUrl;a.download='laxman-ai-voice.wav';a.click()};$('themeBtn').onclick=()=>document.documentElement.classList.toggle('light');speechSynthesis.onvoiceschanged=browserVoices;updateCounter();browserVoices();detect();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
