(()=>{
const $=id=>document.getElementById(id);const V='laxman-ai-voice-v11';let tracks=[];
const state=()=>({subtitles:JSON.parse(localStorage.getItem(V+'-subs')||'[]'),master:+($('masterVolume')?.value||1),music:+($('v11MusicVolume')?.value||.16),duck:+($('v11Duck')?.value||.35)});
const save=()=>localStorage.setItem(V+'-subs',JSON.stringify(state().subtitles));
const toast=(a,b)=>window.setStatus?.(a,b);
function add(){if($('v11Panel'))return;const studio=$('.studio');if(!studio)return;const panel=document.createElement('section');panel.id='v11Panel';panel.className='v11-panel card';panel.innerHTML=`<div class="card-head"><div><h2>🎬 Final Creator Export</h2><p>Master voice, music and subtitles locally in your browser.</p></div><span class="badge">V11 · Offline</span></div><div class="v11-grid"><div><h3>Audio tracks</h3><div class="v11-track"><label>Background music<input id="v11Music" type="file" accept="audio/*" multiple></label><label>Music volume<input id="v11MusicVolume" type="range" min="0" max="1" step=".01" value=".16"></label><label>Voice volume<input id="masterVolume" type="range" min="0" max="1.5" step=".01" value="1"></label><label>Voice ducking<input id="v11Duck" type="range" min="0" max=".8" step=".01" value=".35"></label></div><p class="tiny">Music automatically ducks while narration is active.</p><div class="v11-track"><label>SFX / ambience<input id="v11Sfx" type="file" accept="audio/*" multiple></label><label>SFX volume<input id="v11SfxVolume" type="range" min="0" max="1" step=".01" value=".35"></label></div></div><div><h3>Mastering</h3><div class="master-grid"><label>Target peak <select id="v11Target"><option value="-1">−1 dBFS · YouTube safe</option><option value="-2">−2 dBFS</option><option value="-3">−3 dBFS</option></select></label><label>Limiter<input id="v11Limiter" type="range" min=".7" max="1" step=".01" value=".94"></label></div><button id="v11Preview" class="ghost-btn">▶ Preview final mix</button><button id="v11Wav" class="primary-btn">Export mastered WAV</button><button id="v11Package" class="ghost-btn">📦 YouTube Creator ZIP</button></div></div><div class="v11-sub-head"><div><h3>Subtitle editor</h3><p class="tiny">Edit timing/text before exporting SRT and VTT.</p></div><button id="v11BuildSubs" class="ghost-btn">Build from scenes</button></div><div id="v11Subs" class="v11-subs"><div class="empty-scene">Generate scenes, then build subtitles.</div></div><div class="v11-progress"><span id="v11Progress"></span></div><p id="v11Meta" class="tiny">Final render happens locally; your audio files are not uploaded.</p></section>`;studio.after(panel);$('v11BuildSubs').onclick=buildSubs;$('v11Wav').onclick=()=>exportWav(false);$('v11Package').onclick=()=>exportWav(true);$('v11Preview').onclick=preview;['v11Music','v11Sfx','v11MusicVolume','v11SfxVolume','masterVolume','v11Duck','v11Limiter'].forEach(id=>$(id)?.addEventListener('change',()=>{if(id==='v11Music'||id==='v11Sfx')loadTracks(id)}));renderSubs();}
async function loadTracks(id){for(const f of Array.from($(id)?.files||[])){const buf=await f.arrayBuffer();const ac=new AudioContext();try{const decoded=await ac.decodeAudioData(buf);tracks.push({name:f.name,kind:id==='v11Music'?'music':'sfx',buffer:decoded})}catch{}finally{ac.close()}}toast('Track ready','Local '+(id==='v11Music'?'music':'SFX')+' loaded');}
function buildSubs(){let t=0;const ss=(window.scenes||[]);const old=state().subtitles;const next=[];ss.forEach((s,i)=>{const d=+s.duration||0;next.push({id:i+1,start:+t.toFixed(3),end:+(t+d).toFixed(3),text:s.text||''});t+=d+(+s.after||0)/1000});localStorage.setItem(V+'-subs',JSON.stringify(next));renderSubs();toast('Subtitles built',next.length+' editable cues created')}
function renderSubs(){const host=$('v11Subs');if(!host)return;const subs=state().subtitles;if(!subs.length){host.innerHTML='<div class="empty-scene">No subtitle cues yet.</div>';return}host.innerHTML=subs.map((s,i)=>`<div class="v11-sub" data-i="${i}"><span>${String(i+1).padStart(2,'0')}</span><label>Start<input class="sub-start" type="number" min="0" step=".01" value="${s.start}"></label><label>End<input class="sub-end" type="number" min="0" step=".01" value="${s.end}"></label><textarea class="sub-text">${escapeHtml(s.text)}</textarea><button class="ghost-btn sub-del">Delete</button></div>`).join('');host.querySelectorAll('.v11-sub').forEach(row=>{const i=+row.dataset.i;row.querySelector('.sub-start').oninput=e=>{subs[i].start=Math.max(0,+e.target.value||0);save()};row.querySelector('.sub-end').oninput=e=>{subs[i].end=Math.max(subs[i].start,+e.target.value||0);save()};row.querySelector('.sub-text').oninput=e=>{subs[i].text=e.target.value;save()};row.querySelector('.sub-del').onclick=()=>{subs.splice(i,1);save();renderSubs()}})}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmt(sec,vtt=false){let ms=Math.max(0,Math.round(sec*1000)),h=Math.floor(ms/3600000);ms%=3600000;let m=Math.floor(ms/60000);ms%=60000;let s=Math.floor(ms/1000);ms%=1000;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}${vtt?'.':','}${String(ms).padStart(3,'0')}`}
function subtitleText(){const s=state().subtitles;const srt=s.map((x,i)=>`${i+1}\n${fmt(x.start)} --> ${fmt(x.end)}\n${x.text}\n`).join('\n');const vtt='WEBVTT\n\n'+s.map((x,i)=>`${i+1}\n${fmt(x.start,true)} --> ${fmt(x.end,true)}\n${x.text}\n`).join('\n');return{srt,vtt}}
async function voiceBuffer(){const urls=[];for(const s of window.scenes||[]){if(s.url)urls.push(s.url)}if(!urls.length)throw Error('Generate at least one scene first');const ac=new AudioContext();const bufs=[];for(const u of urls){const b=await fetch(u).then(r=>r.arrayBuffer());bufs.push(await ac.decodeAudioData(b))}const rate=bufs[0].sampleRate,total=bufs.reduce((n,b)=>n+b.duration,0);const out=ac.createBuffer(1,Math.ceil(total*rate),rate);let off=0;for(const b of bufs){out.getChannelData(0).set(b.getChannelData(0),off);off+=b.length}await ac.close();return out}
async function render(){const voice=await voiceBuffer();const rate=voice.sampleRate;const duration=voice.duration;const ac=new OfflineAudioContext(2,Math.ceil(duration*rate),rate);const src=ac.createBufferSource();src.buffer=voice;const vg=ac.createGain();vg.gain.value=+($('masterVolume').value||1);src.connect(vg).connect(ac.destination);src.start();for(const tr of tracks){const x=ac.createBufferSource(),g=ac.createGain();x.buffer=tr.buffer;x.loop=true;g.gain.value=tr.kind==='music'?+($('v11MusicVolume').value||.16):+($('v11SfxVolume').value||.35);if(tr.kind==='music'){const duck=ac.createGain();duck.gain.value=1-(+$('v11Duck').value||.35);x.connect(g).connect(duck).connect(ac.destination)}else x.connect(g).connect(ac.destination);x.start()}const b=await ac.startRendering();return master(b)}
function master(buffer){const target=10**((+$('v11Target').value||-1)/20),limit=+$('v11Limiter').value||.94;let peak=0;for(const ch of buffer.getChannelData(0))peak=Math.max(peak,Math.abs(ch));const gain=peak?Math.min(target/peak,limit/peak):1;for(let c=0;c<buffer.numberOfChannels;c++){const d=buffer.getChannelData(c);for(let i=0;i<d.length;i++){let x=d[i]*gain;d[i]=Math.tanh(x*1.15)/Math.tanh(1.15)}}return buffer}
function wavBlob(b){const n=b.length*2* b.numberOfChannels+44,buf=new ArrayBuffer(n),v=new DataView(buf);let p=0;const w=s=>{for(let i=0;i<s.length;i++)v.setUint8(p++,s.charCodeAt(i))};w('RIFF');v.setUint32(p,36+b.length*b.numberOfChannels*2,true);p+=4;w('WAVEfmt ');v.setUint32(p,16,true);p+=4;v.setUint16(p,1,true);p+=2;v.setUint16(p,b.numberOfChannels,true);p+=2;v.setUint32(p,b.sampleRate,true);p+=4;v.setUint32(p,b.sampleRate*b.numberOfChannels*2,true);p+=4;v.setUint16(p,b.numberOfChannels*2,true);p+=2;v.setUint16(p,16,true);p+=2;w('data');v.setUint32(p,b.length*b.numberOfChannels*2,true);p+=4;for(let i=0;i<b.length;i++)for(let c=0;c<b.numberOfChannels;c++){let x=Math.max(-1,Math.min(1,b.getChannelData(c)[i]));v.setInt16(p,x<0?x*32768:x*32767,true);p+=2}return new Blob([buf],{type:'audio/wav'})}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
async function preview(){try{const b=await render();const a=$('audioPlayer');a.src=URL.createObjectURL(wavBlob(b));a.play();toast('Final mix preview','Mastered voice + local tracks playing')}catch(e){toast('Mix failed',e.message)}}
async function exportWav(pkg){try{$('v11Wav').disabled=true;$('v11Package').disabled=true;$('v11Progress').style.width='25%';toast('Rendering final mix','Mastering narration and local tracks…');const b=await render();$('v11Progress').style.width='75%';const wav=wavBlob(b),subs=subtitleText();if(!pkg){download(wav,'laxman-ai-voice-mastered.wav');$('v11Progress').style.width='100%';toast('WAV exported','Mastered creator audio is ready');return}if(!window.JSZip){await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}const zip=new JSZip();zip.file('final/mastered-narration.wav',wav);zip.file('subtitles/subtitles.srt',subs.srt);zip.file('subtitles/subtitles.vtt',subs.vtt);zip.file('project/scene-manifest.json',JSON.stringify({version:'11.0',duration:Math.round(b.duration*1000)/1000,scenes:(window.scenes||[]).map(s=>({id:s.id,text:s.text,duration:s.duration,speed:s.speed,before:s.before,after:s.after})),subtitles:state().subtitles},null,2));zip.file('README.txt','Laxman AI Voice — YouTube Creator Package\n\nMastered WAV + SRT + VTT + scene manifest.\nGenerated locally in your browser.');const out=await zip.generateAsync({type:'blob'});download(out,'laxman-ai-voice-youtube-package.zip');$('v11Progress').style.width='100%';toast('Creator ZIP ready','YouTube-ready WAV, subtitles and manifest exported')}catch(e){toast('Export failed',e.message)}finally{$('v11Wav').disabled=false;$('v11Package').disabled=false}}
function boot(){add();window.addEventListener('ai-voice-scenes-updated',renderSubs)}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();})();
